### ISSUE TITLE
Uninterruptible takeMVar

### ISSUE THREAD

**Issue by Joel-Speitelsbach** [achirkin/interprocess#1]
I stumbled on this just a few minutes ago:

`takeMVar` and `putMVar` seems to be unresponsive to certain interrupts.

In the program

```
import Control.Concurrent.Async
import Control.Concurrent (threadDelay)
import Control.Concurrent.Process.StoredMVar as M

main :: IO()
main = do
  withAsync
    (M.takeMVar =<< M.newEmptyMVar :: IO Int) $
    \_ -> do
      threadDelay $ 10^6
      print 5
  print 9
```

`9` is never printed.

(This is a Linux x64 machine.)

btw: Thx for sharing your work.

**Comment by achirkin** [comment]
Interesting!
At first, I thought it may have something to do with foreign call blocking the whole capability, but `withAsyncBound` does not work either. Seems like it waits on `throwTo`, even though the `c'mvar_take` call is marked `interruptible`. This needs further investigation. A link to the C code for reference: [`mvar_take`](https://github.com/achirkin/interprocess/blob/466ebc0ae38ec228136c10da73b252e6de2c8066/src/Control/Concurrent/Process/StoredMVar.c#L565-L584).

**Comment by achirkin** [comment]
Just three years later, I've come to fix this bug :tada: The problem indeed was that Haskell sent a SIGPIPE to the thread blocked on the foreign call, but `pthread_condition_wait` function there did not interrupt with EINTR (it's never supposed to do so). The solution was to mask the the signal, replace the wait with the timed wait, and check for the pending SIGPIPE after every timeout.
